version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:14.0.1
    steps:
      - checkout
      - run:
          name: Give permission
          command: chmod +x gradlew
      - run:
          name: Install dependencies
          command: ./gradlew build

workflows:
  workflow:
    jobs:
    - build