/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IntersectionOrderApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test 
    public void list1Empty() 
    {
        ArrayList<Integer> list1 = new ArrayList<>();
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(10, 5, 6, 1, 23, 11));
        assertEquals(-1, App.findTheKthSmallestInIntersection(list1, list2, 1));
    }
    @Test 
    public void list2Empty() 
    {
        ArrayList<Integer> list2 = new ArrayList<>();
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(10, 5, 6, 1, 23, 11));
        assertEquals(-1, App.findTheKthSmallestInIntersection(list1, list2, 1));
    }
    @Test
    public void FirstSmallest()
    {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(10, 5, 6, 1, 23, 11));
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(5, 10, 7, 8, 46, 23));
        assertEquals(5, App.findTheKthSmallestInIntersection(list1, list2, 1));
    }
    @Test
    public void SecondSmallest()
    {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(10, 5, 6, 1, 23, 11));
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(5, 10, 7, 8, 46, 23));
        assertEquals(10, App.findTheKthSmallestInIntersection(list1, list2, 2));
    }
    @Test
    public void ThirdSmallest()
    {
        ArrayList<Integer> list1 = new ArrayList<>(Arrays.asList(10, 5, 6, 1, 23, 11));
        ArrayList<Integer> list2 = new ArrayList<>(Arrays.asList(5, 10, 7, 8, 46, 23));
        assertEquals(23, App.findTheKthSmallestInIntersection(list1, list2, 3));
    }
    @Test
    public void Fail()
    {
        assertEquals(23, 5);
    }
}
